source 'https://cdn.cocoapods.org/'
inhibit_all_warnings!

platform :ios, '9.0'

target 'ExampleForSwift' do
  use_frameworks!
  
  pod 'Masonry', '~> 1.1.0'
  pod 'InjectionIIISupport', '~> 1.2.2', :configurations => 'Debug'
end
